//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldDestinationsWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.UserRatings = new HashSet<UserRating>();
        }
    
        public int PlaceID { get; set; }
        public string Name { get; set; }
        public string Place1 { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string MainPictureURL { get; set; }
        public string CategoryID { get; set; }
        public string Continent { get; set; }
        public string Rating { get; set; }
        public string AltPictureURL { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
    }
}
