//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldDestinationsWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int PlaceID { get; set; }
        public short Rating { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
